server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wer34sf
    url: jdbc:mysql://localhost:3306/testmybatisplus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:com/example/demo/mapper/**/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true